= Viglet Turing ES: README
Viglet Team <opensource@viglet.com>
:organization: Viglet Turing
:toclevels: 5
:toc-title: Table of Content
:viglet-version: 2025.1

[preface]
image:https://img.shields.io/badge/Download-Release%20{viglet-version}-blue?style=for-the-badge&logo=OpenJDK[link="https://viglet.com/turing/download/"]
image:https://img.shields.io/github/license/openturing/turing.svg?style=for-the-badge&logo=Apache["License"]
image:https://img.shields.io/github/last-commit/openturing/turing.svg?style=for-the-badge&logo=java)[GitHub last commit]
image:https://img.shields.io/github/actions/workflow/status/openturing/turing/build.yml?branch=2025.1&style=for-the-badge&logo=GitHub[link="https://github.com/openviglet/turing/actions/workflows/build.yml"]
image:https://img.shields.io/badge/Sonar-Code%20Quality-brightgreen?style=for-the-badge&logo=SonarCloud[link="https://sonarcloud.io/project/overview?id=openviglet_turing"]
image:https://img.shields.io/badge/Javadoc-Release%20{viglet-version}-brightgreen?style=for-the-badge&logo=OpenJDK[link="https://turing.viglet.com/latest/javadoc/"]

== Preface

Viglet Turing (https://viglet.com/turing/) is an enterprise search platform that combines semantic navigation, chatbots, and generative artificial intelligence.

It has several integrations to facilitate enterprise search and interaction with external systems. Some of the main ones include:

- **Authentication APIs**: Allows integration with login and security systems.
- **OCR (Optical Character Recognition)**: Integration to extract text from images and scanned documents.
- **Content Indexing**: Connectors to store and retrieve data from different sources.
- **CMS Connectors**: Support for platforms such as **AEM**, facilitating indexing of managed content.
- **Web Crawler**: Allows indexing of websites and online content.
- **Database**: Connectors for storing and retrieving structured data.
- **File System**: Indexing of local documents and files.
