apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: turing-solr
  name: turing-solr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: turing-solr
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: turing-solr
    spec:
      containers:
        - image: turing-solr
          name: turing-solr
          ports:
            - containerPort: 8983
          resources: {}
      restartPolicy: Always
status: {}
