const consolePath: string = import.meta.env.VITE_CONSOLE_CONTEXT_PATH;
export const ROUTES = {
  ROOT: "/",
  LOGIN: "/login",
  LOGOUT: "/logout",
  CONSOLE: consolePath,
  SN_SEARCH: `/sn`,
  SN_ROOT: `${consolePath}/sn`,
  SN_INSTANCE: `${consolePath}/sn/instance`,
  SE_ROOT: `${consolePath}/se`,
  SE_INSTANCE: `${consolePath}/se/instance`,
  STORE_ROOT: `${consolePath}/store`,
  STORE_INSTANCE: `${consolePath}/store/instance`,
  TOKEN_ROOT: `${consolePath}/token`,
  TOKEN_INSTANCE: `${consolePath}/token/instance`,
  LLM_ROOT: `${consolePath}/llm`,
  LLM_INSTANCE: `${consolePath}/llm/instance`,
  INTEGRATION_ROOT: `${consolePath}/integration`,
  INTEGRATION_INSTANCE: `${consolePath}/integration/instance`,
  LOGGING_ROOT: `${consolePath}/logging`,
  LOGGING_INSTANCE: `${consolePath}/logging/instance`,
  DASHBOARD: `${consolePath}/dashboard`,
};
