package com.viglet.turing.api.llm;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;

import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.viglet.turing.commons.utils.TurCommonsUtils;

import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@RestController
@RequestMapping("/api/v2/code-interpreter")
@Tag(name = "Code Interpreter Files", description = "Serve files generated by the Code Interpreter")
public class TurCodeInterpreterFileAPI {

    private static final String SANDBOX_DIR = "code-interpreter";

    @GetMapping("/{sessionId}/{filename}")
    public ResponseEntity<Resource> getFile(@PathVariable String sessionId, @PathVariable String filename) {
        // Sanitize inputs to prevent path traversal
        if (sessionId.contains("..") || sessionId.contains("/") || sessionId.contains("\\")
                || filename.contains("..") || filename.contains("/") || filename.contains("\\")) {
            return ResponseEntity.badRequest().build();
        }

        File sandboxRoot = TurCommonsUtils.addSubDirToStoreDir(SANDBOX_DIR);
        File file = new File(new File(sandboxRoot, sessionId), filename);

        if (!file.exists() || !file.isFile()) {
            return ResponseEntity.notFound().build();
        }

        // Verify the file is actually inside the sandbox
        if (!file.toPath().normalize().startsWith(sandboxRoot.toPath().normalize())) {
            return ResponseEntity.status(HttpStatus.FORBIDDEN).build();
        }

        try {
            String mimeType = Files.probeContentType(file.toPath());
            if (mimeType == null) {
                mimeType = "application/octet-stream";
            }
            Resource resource = new FileSystemResource(file);
            return ResponseEntity.ok()
                    .contentType(MediaType.parseMediaType(mimeType))
                    .body(resource);
        } catch (IOException e) {
            log.error("Failed to serve code interpreter file {}/{}: {}", sessionId, filename, e.getMessage());
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }
}
